# ARG TAG=16-alpine
# ARG VITE_REPO=https://github.com/vitejs/vite.git
# ARG VITE_DIR=vite

# FROM node:alpine

# ENV VITE_REPO=$VITE_REPO
# ENV VITE_DIR=$VITE_DIR

# WORKDIR /app

# COPY package*.json .

# RUN npm install

# COPY . .

# EXPOSE 3000

# CMD ["npm run dev"]