version: '3.9'
services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    restart: always
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build: ./server
    ports:
      - 3333:3333
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3333
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=devTools
      - DB_PORT=3306
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'